"""rename department

Revision ID: 6e26bd2a383c
Revises: c44b3e968a01
Create Date: 2024-10-02 11:35:38.924407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e26bd2a383c'
down_revision = 'c44b3e968a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    
    # ### end Alembic commands ###
