"""rename adress

Revision ID: e0462e79e567
Revises: 6e26bd2a383c
Create Date: 2024-10-02 11:52:46.556310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0462e79e567'
down_revision = '6e26bd2a383c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('departments', 'address', new_column_name='location')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
